### ISSUE TITLE
No synchronisation within the Shard

### ISSUE THREAD

**Issue by Suzaru** [melroy999/RareTrackerCore#9]
Hey there,

first of all thank you very much for making this addon, it's awesome and I love it.
We are just encountering a weird bug.

While I get "live updates" from other players like [these](https://i.imgur.com/MCv5EHJ.png), my girlfriend will not get any of these shared informations from other players. 

We tried to reinstall everything. Deleted Cache, Interface and WTF folders, reinstalled Core and Maw freshly from wowup. Nothing helped. Do you have any idea what we are missing?

Thank you for your time and effort!

Cheers

**Comment by melroy999** [comment]
Hello,

I suspect that your girlfriend's client somehow cannot join the hidden channel in which the addon communicates with other clients.

I presume that you and your girlfriend both are on the same realm? If not, this might be the cause of this issue, since channels only work for players on the same realm/connected realms due to limits put on these channels. To see which channels are active, you can right click on the general chat tab, go Filters > Settings, and then look in the Channels list. In this list, there should be a channel of the format RT[numbers]S[numbers]. Is such a channel present and does it match with your own?

**Comment by Suzaru** [comment]
Thank you for your quick reply! 

We are from different realms, but we check that already and we are both in these channels. They are called the exact same.

**Comment by melroy999** [comment]
No problem!

Yes, it would indeed be nice if there was an alternative… when grouped, your own client should still be able to communicate with hers, but only if you yourself are damaging the rare or vice versa.

Theoretically it would be possible to relay all messages received to the party chat as well, but this is unfortunately impractical due to the explosive number of communicational messages that it might result in—in the best case they would be throttled, but as some addon authors have learned in the past, it might get users banned too. I’d rather not take that risk, so I unfortunately can’t produce any meaningful fix for this issue.

**Comment by Suzaru** [comment]
Well I thank you very much anyways! I guess realm transfer it is then! :) Thank you for your effort and support!
